---
title: "Reward/Penalty behavioral data analysis"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r include=FALSE}
library(dplyr)
library(tidyr)
library(forcats)
library(lme4)
library(sjPlot)
library(ggplot2)
library(ggtext)
library(psych)
library(simr)
library(gridExtra)
library(Rmisc)
library(MASS)


gg.rr <-theme(axis.line = element_line(colour = "black"),text = element_text(family='Arial',size=11),
        axis.title.y = element_markdown(margin = margin(t = 20, r = 5, b = 20, l = 0)),
        axis.title.x = element_markdown(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    strip.background = element_blank(),
    plot.title = element_markdown(hjust = 0.5,size=12))

gg.side <-theme(axis.line = element_line(colour = "black"),text = element_text(family='Arial',size=11),
        axis.title.y = element_markdown(margin = margin(t = 0, r = 5, b = 0, l = 0)),
        axis.title.x = element_markdown(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    strip.background = element_blank(),
    plot.title = element_markdown(hjust = 0.5,size=12))

```


```{r include=FALSE}
library(extrafont)

loadfonts()
```

# Study 1

## Load and process data

```{r}
df.subject <- read.csv('data/Study1/participant_data_1.csv') %>%
  mutate(gender=factor(gender),
         scaledAge=scale(age))

df.trial<- read.csv('data/Study1/behavioral_data_1.csv') %>%
  mutate(catPunLevel=factor(catPunLevel),
         catRewLevel=factor(catRewLevel),
         catCong=factor(catCong)) %>% 
  filter(RT>=250)
```


```{r}

df.interval<-df.trial %>% group_by(subj_idx,IntervalDur,globalIntervalNum,catRewLevel,catPunLevel) %>%
  dplyr::summarize(meanCongruency=mean(Congruency),
                   norm_sum_Acc=sum(Acc,na.rm = T)/mean(IntervalDur),
                   mean_Acc=mean(Acc,na.rm=T),
                   mean_AccRT=mean(AccRT,na.rm=T),
                   mean_RT=mean(RT),
                   nTrial=n()) %>% ungroup() %>%
  filter(abs(meanCongruency-0.5)<=0.2,mean_Acc>=0.6) %>%
  mutate(scaledMeanCong=scale(meanCongruency),
         subj_idx=as.character(subj_idx),
         scaledDur=(IntervalDur-10)/2,
         scaledGlobalIntervalNum=(globalIntervalNum-39.5)/39.5)

df.trial <- inner_join(df.trial,df.interval %>% 
                         dplyr::select(subj_idx,globalIntervalNum,scaledGlobalIntervalNum,
                                       scaledMeanCong,nTrial,meanCongruency),
                       by=c('subj_idx','globalIntervalNum')) %>% filter(RT<=3000)

df.interval.combined<-inner_join(df.interval,df.subject,by='subj_idx') %>%
  mutate(catRewLevel=relevel(catRewLevel,ref='High Reward'),
         catPunLevel=relevel(catPunLevel,ref='High Penalty'))

df.trial.combined<-inner_join(df.trial,df.subject,by='subj_idx') %>%
  mutate(catRewLevel=relevel(catRewLevel,ref='High Reward'),
         catPunLevel=relevel(catPunLevel,ref='High Penalty'),
         catCong=relevel(catCong,ref='congruent'),
         scaledRT=scale(log10(RT)),
         scaledTrialNum=scale(TrialNum))

df.trial.combined.acc<-df.trial.combined %>% filter(Acc==1) %>%
  mutate(scaledTrialNum=scale(TrialNum))
```

```{r}
df.trial.hddm.re <- df.trial %>% filter(subj_idx %in% df.subject$subj_idx,isRandom==FALSE) %>%
  mutate(rt=RT/1000,
         response=Acc,
         subj_idx=as.numeric(factor(subj_idx))) %>% dplyr::select(subj_idx,rt,response,catRewLevel,catPunLevel,catCong)

write.csv(df.trial.hddm.re,'data/Study1/hddm_data_ae_only.csv',col.names = T,row.names = F)

df.trial.hddm <- df.trial %>% filter(subj_idx %in% df.subject$subj_idx) %>%
  mutate(rt=RT/1000,
         response=Acc,
         subj_idx=as.numeric(factor(subj_idx))) %>% dplyr::select(subj_idx,rt,response,catRewLevel,catPunLevel,catCong)

write.csv(df.trial.hddm,'data/Study1/hddm_data.csv',col.names = T,row.names = F)
```

## Interval-level model

```{r, message=FALSE, warning=FALSE}
contrasts(df.interval.combined$catPunLevel)<-contr.sum
contrasts(df.interval.combined$catRewLevel)<-contr.sum
contrasts(df.interval.combined$gender)<-contr.sum
```

```{r message=TRUE, warning=TRUE}
model.rr<-lmerTest::lmer(norm_sum_Acc ~ scaledAge + gender + catPunLevel * catRewLevel + scaledGlobalIntervalNum + scaledMeanCong + (1 + catPunLevel * catRewLevel + scaledGlobalIntervalNum + scaledMeanCong|subj_idx),data=df.interval.combined)
summary(model.rr)
sv1_max <- svd(getME(model.rr,"Tlist")[[1]])
sv1_max$d
round(sv1_max$d^2/sum(sv1_max$d^2)*100, 1)

tab_model(model.rr,show.icc = F,show.re.var = F,show.se=T,digits = 3,show.ci=F,
          pred.labels = c("Intercept","Age","Female - Male",
                          "High Penalty - Low Penalty",
                          "High Reward - Low Reward",
                          "Interval Num",
                          "Average Congruence",
                          "Reward X Penalty"),
          dv.labels = c("Correct Responses Per Second"),
          string.se = "S.E.",
          string.p = "P-Value"
          )

anova(model.rr)
```
## Trial-level model

```{r}
contrasts(df.trial.combined$catPunLevel)<-contr.sum
contrasts(df.trial.combined$catRewLevel)<-contr.sum
contrasts(df.trial.combined$gender)<-contr.sum
contrasts(df.trial.combined$catCong)<-contr.sum
contrasts(df.trial.combined.acc$catPunLevel)<-contr.sum
contrasts(df.trial.combined.acc$catRewLevel)<-contr.sum
contrasts(df.trial.combined.acc$gender)<-contr.sum
contrasts(df.trial.combined.acc$catCong)<-contr.sum
```



```{r message=TRUE, warning=TRUE}
model.accrt.t<-lmerTest::lmer(log10(AccRT/1000)~scaledAge + gender + catPunLevel * catRewLevel * catCong + scaledTrialNum + scaledGlobalIntervalNum + (1 + catPunLevel * catRewLevel * catCong + scaledTrialNum + scaledGlobalIntervalNum|subj_idx),data=df.trial.combined.acc)
summary(model.accrt.t)
sv1_max <- svd(getME(model.accrt.t,"Tlist")[[1]])
sv1_max$d
round(sv1_max$d^2/sum(sv1_max$d^2)*100, 1)
anova(model.accrt.t)
```


```{r}
model.acc.t<-glmer(Acc ~ scaledAge + gender + catPunLevel * catRewLevel * catCong + scaledTrialNum + scaledGlobalIntervalNum + (1 + catPunLevel * catRewLevel * catCong + scaledTrialNum + scaledGlobalIntervalNum|subj_idx),family=binomial,data=df.trial.combined)
summary(model.acc.t)
tab_model(model.acc.t,show.icc = F,show.re.var = F)
sv1_max <- svd(getME(model.acc.t,"Tlist")[[1]])
sv1_max$d
round(sv1_max$d^2/sum(sv1_max$d^2)*100, 1)
```


```{r}
tab_model(model.accrt.t,model.acc.t,show.icc = F,
          show.re.var = F,digits=3,
          show.se = T,
          show.ci = F,
          pred.labels = c("Intercept","Age","Female - Male",
                          "High Penalty - Low Penalty",
                          "High Reward - Low Reward",
                          "Trial Congruence (Cong-Incong)",
                          "Trial Number",
                          "Interval Number",
                          "Reward X Penalty",
                          "Penalty X Congruence",
                          "Reward X Congruence",
                          "Reward X Penalty X Congruence"),
          dv.labels = c("Log-Transformed RT","Accuracy"),
          string.se = "S.E.",
          string.p = "P-Value")
```


```{r}
car::Anova(model.acc.t)
```

## Plot figures

```{r}
df.plot <- df.interval.combined %>% mutate(catRewLevel=relevel(catRewLevel,ref='Low Reward'),
                       catPunLevel=relevel(catPunLevel,ref='Low Penalty'),
                       mean_AccRT=mean_AccRT/1000)

df.trial.plot <- df.trial.combined %>% mutate(catRewLevel=relevel(catRewLevel,ref='Low Reward'),
                       catPunLevel=relevel(catPunLevel,ref='Low Penalty'),
                       AccRT=AccRT/1000)
```


```{r}
dfwc.p.acc<-summarySEwithin(df.trial.plot, measurevar="Acc", withinvars=c("catPunLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pp.acc <- ggplot() + 
  geom_errorbar(data=dfwc.p.acc,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=Acc - ci, ymax=Acc + ci,color=catPunLevel)) +
  geom_point(data=dfwc.p.acc,aes(x=catPunLevel,y=Acc,color=catPunLevel),stat='identity',size=3) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#8C3E00"),guide='none') + ylab('<b>Accuracy</b><br>') + xlab("<b>Penalty</b>") +
  coord_cartesian(ylim = c(0.93,0.98)) + 
  scale_y_continuous(breaks = c(0.94,0.96,0.98)) + scale_x_discrete(labels=c("High Penalty" = "High", "Low Penalty" = "Low"))

dfwc.p.accrt<-summarySEwithin(df.trial.plot, measurevar="AccRT", withinvars=c("catPunLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pp.accrt <- ggplot() + 
  geom_errorbar(data=dfwc.p.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catPunLevel)) +
  geom_point(data=dfwc.p.accrt,aes(x=catPunLevel,y=AccRT,color=catPunLevel),stat='identity',size=3) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#8C3E00"),guide='none') + 
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("<b>Penalty</b>") +coord_cartesian(ylim = c(0.75,0.85)) + 
  scale_y_continuous(breaks = c(0.75,0.8,0.85)) + scale_x_discrete(labels=c("High Penalty" = "High", "Low Penalty" = "Low"))

dfwc.p.rr<-summarySEwithin(df.plot, measurevar="norm_sum_Acc", withinvars=c("catPunLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pp.rr <- ggplot() + 
  geom_errorbar(data=dfwc.p.rr,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=norm_sum_Acc-ci, ymax=norm_sum_Acc +ci,color=catPunLevel)) + 
  geom_point(data=dfwc.p.rr,aes(x=catPunLevel,y=norm_sum_Acc,color=catPunLevel),stat='identity',size=3) + gg.rr + 
  scale_color_manual(name = "",values=c("#D96000","#8C3E00"),guide='none') + ylab("<b>Correct Responses Per Second</b>") + xlab("<b>Penalty</b>") +
  coord_cartesian(ylim = c(1.05,1.2)) + 
  scale_y_continuous(breaks = c(1.1,1.2)) + scale_x_discrete(labels=c("High Penalty" = "High", "Low Penalty" = "Low"))

dfwc.r.acc<-summarySEwithin(df.trial.plot, measurevar="Acc", withinvars=c("catRewLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pr.acc <- ggplot() +
  geom_errorbar(data=dfwc.r.acc,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=Acc-ci, ymax=Acc +ci,color=catRewLevel)) + 
  geom_point(data=dfwc.r.acc,aes(x=catRewLevel,y=Acc,color=catRewLevel),stat='identity',size=3) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#005E5E"),guide='none') + ylab('<b>Accuracy</b><br>') + xlab("<b>Reward</b>") +
  coord_cartesian(ylim = c(0.93,0.98)) + 
  scale_y_continuous(breaks = c(0.94,0.96,0.98)) + scale_x_discrete(labels=c("High Reward" = "High", "Low Reward" = "Low"))
 
dfwc.r.accrt<-summarySEwithin(df.trial.plot, measurevar="AccRT", withinvars=c("catRewLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pr.accrt <- ggplot() + 
  geom_errorbar(data=dfwc.r.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catRewLevel)) +
  geom_point(data=dfwc.r.accrt,aes(x=catRewLevel,y=AccRT,color=catRewLevel),stat='identity',size=3) + 
  scale_color_manual(name = "",values=c("#00D9D9","#005E5E"),guide='none') + 
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("<b>Reward</b>") +coord_cartesian(ylim = c(0.75,0.85)) + 
  scale_y_continuous(breaks = c(0.75,0.8,0.85)) + scale_x_discrete(labels=c("High Reward" = "High", "Low Reward" = "Low")) + gg.side
 
dfwc.r.rr<-summarySEwithin(df.plot, measurevar="norm_sum_Acc", withinvars=c("catRewLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pr.rr <- ggplot() +
  geom_errorbar(data=dfwc.r.rr,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=norm_sum_Acc-ci, ymax=norm_sum_Acc +ci,color=catRewLevel)) + 
  geom_point(data=dfwc.r.rr,aes(x=catRewLevel,y=norm_sum_Acc,color=catRewLevel),stat='identity',size=3) + 
  gg.rr + 
  scale_color_manual(name = "",values=c("#00D9D9","#005E5E"),guide='none') + ylab("<b>Correct Responses Per Second</b>") + xlab("<b>Reward</b>") +
  coord_cartesian(ylim = c(1.05,1.2)) + 
  scale_y_continuous(breaks = c(1.1,1.2)) + scale_x_discrete(labels=c("High Reward" = "High", "Low Reward" = "Low"))
```



```{r}
# pdf("whatever.pdf",width = 12,height = 6)
lay <- rbind(c(NA,2,NA,NA,5),
             c(1,2,NA,4,5),
             c(1,3,NA,4,6),
             c(NA,3,NA,NA,6))
a<-grid.arrange(grobs = list(pr.rr,pr.accrt,pr.acc,pp.rr,pp.accrt,pp.acc), layout_matrix = lay,widths=unit(c(4,4,1,4,4), c("cm", "cm")),heights=unit(c(1,3.5,3.5,1),c('cm','cm')))
# dev.off()
# embed_fonts("whatever.pdf",outfile = 'test.pdf')
ggsave(filename = 'Figures/Figure2.pdf',a,units = 'cm',width = 20,height = 10)
```

```{r}
df.trial.plot$catCong <- factor(df.trial.plot$catCong,labels=c('Congruent','Incongruent'))

dfwc.p.acc<-summarySEwithin(df.trial.plot, measurevar="Acc", withinvars=c("catPunLevel","catCong"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pp.acc <- ggplot() + geom_line(data=dfwc.p.acc,position = position_dodge(.6),aes(x=catPunLevel,y=Acc,linetype=catCong,group=catCong)) +
  geom_errorbar(data=dfwc.p.acc,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=Acc - ci, ymax=Acc + ci,color=catPunLevel,group=catCong)) +
  geom_point(data=dfwc.p.acc,position = position_dodge(.6),aes(x=catPunLevel,y=Acc,color=catPunLevel,shape=catCong,group=catCong),stat='identity',size=1.5) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#8C3E00"),guide = 'none') + ylab('<b>Accuracy</b><br>') + xlab("Penalty") +
  coord_cartesian(ylim = c(0.935,0.98)) + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  scale_y_continuous(breaks = c(0.94,0.96,0.98)) + scale_x_discrete(labels=c("High Penalty" = "High", "Low Penalty" = "Low"))

dfwc.p.accrt<-summarySEwithin(df.trial.plot, measurevar="AccRT", withinvars=c("catPunLevel","catCong"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pp.accrt <- ggplot() + geom_line(data=dfwc.p.accrt,position = position_dodge(.6),aes(x=catPunLevel,y=AccRT,linetype=catCong,group=catCong)) +
  geom_errorbar(data=dfwc.p.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catPunLevel,group=catCong)) +
  geom_point(data=dfwc.p.accrt,position = position_dodge(.6),aes(x=catPunLevel,y=AccRT,color=catPunLevel,shape=catCong,group=catCong),stat='identity',size=1.5) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#8C3E00"),guide = 'none') + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("Penalty") +coord_cartesian(ylim = c(0.7,0.9)) + 
  scale_y_continuous(breaks = c(0.7,0.8,0.9)) + scale_x_discrete(labels=c("High Penalty" = "High", "Low Penalty" = "Low"))

dfwc.p.rr<-summarySEwithin(df.plot, measurevar="norm_sum_Acc", withinvars=c("catPunLevel"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

dfwc.r.acc<-summarySEwithin(df.trial.plot, measurevar="Acc", withinvars=c("catRewLevel","catCong"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pr.acc <- ggplot() + geom_line(data=dfwc.r.acc,position = position_dodge(.6),aes(x=catRewLevel,y=Acc,linetype=catCong,group=catCong)) +
  geom_errorbar(data=dfwc.r.acc,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=Acc-ci, ymax=Acc +ci,color=catRewLevel,group=catCong)) + 
  geom_point(data=dfwc.r.acc,position = position_dodge(.6),aes(x=catRewLevel,y=Acc,color=catRewLevel,shape=catCong,group=catCong),stat='identity',size=1.5) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#005E5E"),guide = 'none') + ylab('<b>Accuracy</b><br>') + xlab("Reward") +
  coord_cartesian(ylim = c(0.935,0.98)) + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  scale_y_continuous(breaks = c(0.94,0.96,0.98)) + scale_x_discrete(labels=c("High Reward" = "High", "Low Reward" = "Low"))
 
dfwc.r.accrt<-summarySEwithin(df.trial.plot, measurevar="AccRT", withinvars=c("catRewLevel","catCong"),idvar="mTurkID",na.rm=TRUE, conf.interval=.95)

pr.accrt <- ggplot() + geom_line(data=dfwc.r.accrt,position = position_dodge(.6),aes(x=catRewLevel,y=AccRT,linetype=catCong,group=catCong)) +
  geom_errorbar(data=dfwc.r.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catRewLevel,group=catCong)) +
  geom_point(data=dfwc.r.accrt,position = position_dodge(.6),aes(x=catRewLevel,y=AccRT,color=catRewLevel,shape=catCong,group=catCong),stat='identity',size=1.5) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#005E5E"),guide = 'none') + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("Reward") +coord_cartesian(ylim = c(0.7,0.9)) + 
  scale_y_continuous(breaks = c(0.7,0.8,0.9)) + scale_x_discrete(labels=c("High Reward" = "High", "Low Reward" = "Low"))

```


```{r}
lay <- rbind(c(1,NA,3),
             c(2,NA,4))

plots <- list(pr.accrt,pr.acc,pp.accrt,pp.acc)
grobs <- list()
widths <- list()

for (i in 1:length(plots)){
    grobs[[i]] <- ggplotGrob(plots[[i]])
    widths[[i]] <- grobs[[i]]$widths[2:5]
}

maxwidth <- do.call(grid::unit.pmax, widths)

for (i in 1:length(grobs)){
     grobs[[i]]$widths[2:5] <- as.list(maxwidth)
}
p<-grid.arrange(grobs = grobs, layout_matrix = lay,widths=unit(c(5,0.5,5), c("cm", "cm")),heights=unit(c(5,5),c('cm','cm')))

ggsave(filename = 'Figures/Figure7_cong_combined.pdf',p,units = 'cm',width = 22,height = 11)
```


# Study 2

## Load and process data 

```{r}
df.subject <- read.csv('data/Study2/participant_data_2.csv') %>%
  mutate(scaledAge=scale(age),
         gender=factor(gender))
df.trial <- read.csv('data/Study2/behavioral_data_2.csv') %>%
    mutate(catPunLevel=factor(catPunLevel,levels = c('Low Penalty','Medium Penalty','High Penalty')),
         catRewLevel=factor(catRewLevel,levels = c('Low Reward','Medium Reward','High Reward')),
         catCong=factor(catCong)) %>% 
    filter(rt>=250)
```

```{r include=FALSE}
df.interval <- df.trial %>% 
  group_by(subj_idx,intervalNum,blockNum,intervalLength,intervalType,
           catRewLevel,catPunLevel,globalIntervalNum) %>% 
  dplyr::summarise(mean_Acc=mean(hit,na.rm=T),
                   norm_sum_Acc=sum(hit,na.rm=T),
                   mean_AccRT=mean(AccRT,na.rm=T),
                   mean_RT=mean(rt,na.rm=T),
                   mean_Congruence=mean(Congruency,na.rm=T)) %>% ungroup() %>%
  mutate(norm_sum_Acc=norm_sum_Acc/intervalLength*1000,
         scaledIntervalDur=(intervalLength/1000-7.5)/1.5,
         log10_AccRT=log10(mean_AccRT)) %>% 
  filter(mean_Acc>=0.6,mean_Congruence>=0.3,mean_Congruence<=0.7) %>%
  mutate(scaledGlobalIntervalNum=(globalIntervalNum-35.5)/35.5,
         scaledMeanCong=scale(mean_Congruence))
```


```{r}
df.trial<-inner_join(df.trial,df.interval %>% dplyr::select(subj_idx,globalIntervalNum),
                               by=c('subj_idx','globalIntervalNum')) %>%
  filter(rt<=3000)

df.trial.combined <- inner_join(df.trial,df.subject,by=c('subj_idx')) %>%
  mutate(scaledTrialNum=scale(trialNum))
df.trial.combined.acc <- df.trial.combined %>% filter(hit==1) %>% 
  mutate(scaledTrialNum=scale(trialNum))
df.interval.combined <- inner_join(df.interval,df.subject,by=c('subj_idx'))
```


```{r}
df.trial.hddm.re <- df.trial %>% filter(isRandom==FALSE) %>%
  mutate(rt=rt/1000,
         response=hit,
         subj_idx=as.numeric(factor(subj_idx)),
         catCong=type) %>% 
  dplyr::select(subj_idx,rt,response,catRewLevel,catPunLevel,catCong)

write.csv(df.trial.hddm.re,'data/Study2/hddm_data_ae_only.csv',col.names = T,row.names = F)

df.trial.hddm <- df.trial %>% 
  mutate(rt=rt/1000,
         response=hit,
         subj_idx=as.numeric(factor(subj_idx)),
         catCong=type) %>% 
  dplyr::select(subj_idx,rt,response,catRewLevel,catPunLevel,catCong)

write.csv(df.trial.hddm,'data/Study2/hddm_data.csv',col.names = T,row.names = F)
```

## Interval-level model

```{r}
contrasts(df.interval.combined$catPunLevel)<-contr.sdif(3)
contrasts(df.interval.combined$catRewLevel)<-contr.sdif(3)
contrasts(df.interval.combined$gender)<-contr.sum
```


```{r}
model.rr <- lmerTest::lmer(norm_sum_Acc ~ scaledAge + gender + catRewLevel + catPunLevel + scaledMeanCong + scaledGlobalIntervalNum + 
                             (1 + catRewLevel + catPunLevel + scaledMeanCong + scaledGlobalIntervalNum|subj_idx),
                           df.interval.combined)
anova(model.rr)
```


```{r}
tab_model(model.rr,show.icc = F,show.re.var = F,show.se=T,digits = 3,show.ci=F,
          pred.labels = c("Intercept","Age","Female - Male",
                          "Medium Reward - Low Reward",
                          "High Reward - Medium Reward",
                          "Medium Penalty - Low Penalty",
                          "High Penalty - Medium Penalty",
                          "Average Congruence",
                          "Interval Number"),
          dv.labels = c("Correct Responses Per Second"),
          string.se = "S.E.",
          string.p = "P-Value")
```

## Trial-level model

```{r}
contrasts(df.trial.combined$catPunLevel)<-contr.sdif(3)
contrasts(df.trial.combined$catRewLevel)<-contr.sdif(3)
contrasts(df.trial.combined$catCong)<-contr.sum
contrasts(df.trial.combined$gender)<-contr.sum
```

```{r}
model.acc.trial<-glmer(hit ~ scaledAge + gender + catRewLevel + catPunLevel + catCong +
                         (1 + catRewLevel + catPunLevel + catCong|subj_idx),df.trial.combined,
                       family = binomial)

car::Anova(model.acc.trial)
```



```{r}
model.acc.trial<-glmer(hit ~ scaledAge + gender + type * catPunLevel + type * catRewLevel + 
                         (1 + type * catPunLevel + type * catRewLevel|subj_idx),df.trial.combined,
                       family = binomial)

car::Anova(model.acc.trial)
```




```{r}
model.accrt.trial<-lmerTest::lmer(log10(AccRT) ~ scaledAge + gender + catRewLevel + catPunLevel + type +
                         (1 + catRewLevel + catPunLevel + type|subj_idx),df.trial.combined.acc)
anova(model.accrt.trial)
```

```{r}
model.accrt.trial<-lmerTest::lmer(log10(AccRT) ~ scaledAge + gender + catRewLevel*type + catPunLevel * type +
                         (1 + catRewLevel*type + catPunLevel * type|subj_idx),df.trial.combined.acc)
anova(model.accrt.trial)
```

```{r}
tab_model(model.accrt.trial,model.acc.trial,show.icc = F,show.re.var = F,show.se=T,digits = 3,show.ci=F,
          pred.labels = c("Intercept","Age","Female - Male",
                          "Medium Reward - Low Reward",
                          "High Reward - Medium Reward",
                          "Medium Penalty - Low Penalty",
                          "High Penalty - Medium Penalty",
                          "Trial Congruence (Cong-Incong)"),
          dv.labels = c("Log-transformed RT","Accuracy"),
          string.se = "S.E.",
          digits.p = 4,
          string.p = "P-Value")
```


## Plot figures


```{r}
dfwc.p.rr<-summarySEwithin(df.interval.combined, measurevar="norm_sum_Acc", withinvars=c("catPunLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pp.rr <- ggplot() + 
  geom_line(data=dfwc.p.rr,aes(x=catPunLevel,y=norm_sum_Acc,group=1)) +
  geom_errorbar(data=dfwc.p.rr,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=norm_sum_Acc-ci, ymax=norm_sum_Acc +ci,color=catPunLevel)) + geom_point(data=dfwc.p.rr,aes(x=catPunLevel,y=norm_sum_Acc,color=catPunLevel),stat='identity',size=3) + 
  gg.rr + scale_color_manual(name = "",values=c("#D96000","#B34F00","#8C3E00"),guide=FALSE) + ylab("<b>Correct Responses Per Second</b>") + xlab("<b>Penalty</b>") + coord_cartesian(ylim = c(1,1.12)) + scale_y_continuous(breaks = c(1,1.1)) + scale_x_discrete(labels=c("High Penalty" = "High","Medium Penalty" = "Medium","Low Penalty" = "Low"))


dfwc.p.accrt<-summarySEwithin(df.trial.combined, measurevar="AccRT", withinvars=c("catPunLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pp.accrt <- ggplot() + geom_line(data=dfwc.p.accrt,aes(x=catPunLevel,y=AccRT,group=1)) +
  geom_errorbar(data=dfwc.p.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catPunLevel)) +  geom_point(data=dfwc.p.accrt,aes(x=catPunLevel,y=AccRT,color=catPunLevel),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#B34F00","#8C3E00"),guide=FALSE) + ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("<b>Penalty</b>") +coord_cartesian(ylim = c(0.8,0.9)) + 
  scale_y_continuous(breaks = c(0.8,0.9)) + scale_x_discrete(labels=c("High Penalty" = "High","Medium Penalty" = "Medium","Low Penalty" = "Low"))

dfwc.p.acc<-summarySEwithin(df.trial.combined, measurevar="hit", withinvars=c("catPunLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pp.acc <- ggplot() + geom_line(data=dfwc.p.acc,aes(x=catPunLevel,y=hit,group=1)) +
  geom_errorbar(data=dfwc.p.acc,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=hit - ci, ymax=hit + ci,color=catPunLevel)) + geom_point(data=dfwc.p.acc,aes(x=catPunLevel,y=hit,color=catPunLevel),stat='identity',size=2)+gg.side +
  scale_color_manual(name = "",values=c("#D96000","#B34F00","#8C3E00"),guide=FALSE) + ylab('<b>Accuracy</b><br>') + xlab("<b>Penalty</b>") +coord_cartesian(ylim = c(0.95,0.98)) + scale_y_continuous(breaks = c(0.95,0.98)) + scale_x_discrete(labels=c("High Penalty" = "High","Medium Penalty" = "Medium","Low Penalty" = "Low"))

dfwc.r.rr<-summarySEwithin(df.interval.combined, measurevar="norm_sum_Acc", withinvars=c("catRewLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pr.rr <- ggplot() + geom_line(data=dfwc.r.rr,aes(x=catRewLevel,y=norm_sum_Acc,group=1)) +
  geom_errorbar(data=dfwc.r.rr,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=norm_sum_Acc-ci, ymax=norm_sum_Acc +ci,color=catRewLevel)) + geom_point(data=dfwc.r.rr,aes(x=catRewLevel,y=norm_sum_Acc,color=catRewLevel),stat='identity',size=3) + gg.rr + scale_color_manual(name = "",values=c("#00D9D9","#00A3A3","#005E5E"),guide=FALSE) + ylab("<b>Correct Responses Per Second</b>") + xlab("<b>Reward</b>") + coord_cartesian(ylim = c(1,1.12)) + 
  scale_y_continuous(breaks = c(1,1.1)) + scale_x_discrete(labels=c("High Reward" = "High","Medium Reward" = "Medium","Low Reward" = "Low"))

dfwc.r.accrt<-summarySEwithin(df.trial.combined, measurevar="AccRT", withinvars=c("catRewLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pr.accrt <- ggplot() + geom_line(data=dfwc.r.accrt,aes(x=catRewLevel,y=AccRT,group=1)) +
  geom_errorbar(data=dfwc.r.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catRewLevel)) +  geom_point(data=dfwc.r.accrt,aes(x=catRewLevel,y=AccRT,color=catRewLevel),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#00A3A3","#005E5E"),guide=FALSE) + ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("<b>Reward</b>") +coord_cartesian(ylim = c(0.8,0.9)) + 
  scale_y_continuous(breaks = c(0.8,0.9)) + scale_x_discrete(labels=c("High Reward" = "High","Medium Reward" = "Medium","Low Reward" = "Low"))

dfwc.r.acc<-summarySEwithin(df.trial.combined, measurevar="hit", withinvars=c("catRewLevel"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pr.acc <- ggplot() + geom_line(data=dfwc.r.acc,aes(x=catRewLevel,y=hit,group=1)) +
  geom_errorbar(data=dfwc.r.acc,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=hit - ci, ymax=hit + ci,color=catRewLevel)) + geom_point(data=dfwc.r.acc,aes(x=catRewLevel,y=hit,color=catRewLevel),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#00A3A3","#005E5E"),guide=FALSE) + ylab('<b>Accuracy</b><br>') + xlab("<b>Reward</b>") + coord_cartesian(ylim = c(0.95,0.98)) + 
  scale_y_continuous(breaks = c(0.95,0.98)) + scale_x_discrete(labels=c("High Reward" = "High","Medium Reward" = "Medium","Low Reward" = "Low"))

```


```{r}
# pdf("whatever.pdf",width = 12,height = 6)
lay <- rbind(c(1,3,NA,2,5),
             c(1,4,NA,2,6))

plots <- list(pr.accrt,pr.acc,pp.accrt,pp.acc)
grobs <- list()
widths <- list()

for (i in 1:length(plots)){
    grobs[[i]] <- ggplotGrob(plots[[i]])
    widths[[i]] <- grobs[[i]]$widths[2:5]
}

maxwidth <- do.call(grid::unit.pmax, widths)

for (i in 1:length(grobs)){
     grobs[[i]]$widths[2:5] <- as.list(maxwidth)
}

grobs <- list(ggplotGrob(pr.rr),ggplotGrob(pp.rr),grobs[[1]],grobs[[2]],grobs[[3]],grobs[[4]])

a<-grid.arrange(grobs = grobs, layout_matrix = lay,widths=unit(c(6,5.5,1,6,5.5), c("cm", "cm")),heights=unit(c(4.5,4.5),c('cm','cm')))
# dev.off()
# embed_fonts("whatever.pdf",outfile = 'test.pdf')
ggsave(filename = 'Figures/Figure6.pdf',a,units = 'cm',width = 25,height = 10)
```


```{r}

df.trial.combined$type <- factor(df.trial.combined$catCong,labels=c('Congruent','Incongruent'))

dfwc.p.acc<-summarySEwithin(df.trial.combined, measurevar="hit", withinvars=c("catPunLevel","catCong"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pp.acc <- ggplot() + geom_line(data=dfwc.p.acc,position=position_dodge(.6),aes(x=catPunLevel,y=hit,group=catCong,linetype=catCong)) + 
  geom_errorbar(data=dfwc.p.acc,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=hit - ci, ymax=hit + ci,color=catPunLevel,group=catCong)) +
  geom_point(data=dfwc.p.acc,position = position_dodge(.6),aes(x=catPunLevel,y=hit,color=catPunLevel,shape=catCong,group=catCong),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#B34F00","#8C3E00"),guide = 'none') + ylab('<b>Accuracy</b><br>') + xlab("Penalty") +
  coord_cartesian(ylim = c(0.95,0.98)) + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  scale_y_continuous(breaks = c(0.96,0.98)) + scale_x_discrete(labels=c("High Penalty" = "High","Medium Penalty" = "Medium","Low Penalty" = "Low"))

dfwc.p.accrt<-summarySEwithin(df.trial.combined, measurevar="AccRT", withinvars=c("catPunLevel","catCong"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pp.accrt <- ggplot() + geom_line(data=dfwc.p.accrt,position=position_dodge(.6),aes(x=catPunLevel,y=AccRT,group=catCong,linetype=catCong)) +
  geom_errorbar(data=dfwc.p.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catPunLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catPunLevel,group=catCong)) +
  geom_point(data=dfwc.p.accrt,position=position_dodge(.6),aes(x=catPunLevel,y=AccRT,color=catPunLevel,shape=catCong,group=catCong),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#D96000","#B34F00","#8C3E00"),guide = 'none') + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("Penalty") +coord_cartesian(ylim = c(0.75,0.9)) + 
  scale_y_continuous(breaks = c(0.8,0.9)) + scale_x_discrete(labels=c("High Penalty" = "High","Medium Penalty" = "Medium","Low Penalty" = "Low"))

dfwc.r.acc<-summarySEwithin(df.trial.combined, measurevar="hit", withinvars=c("catRewLevel","catCong"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pr.acc <- ggplot() + geom_line(data=dfwc.r.acc,position=position_dodge(.6),aes(x=catRewLevel,y=hit,group=catCong,linetype=catCong)) +
  geom_errorbar(data=dfwc.r.acc,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=hit-ci, ymax=hit +ci,color=catRewLevel,group=catCong)) + 
  geom_point(data=dfwc.r.acc,position = position_dodge(.6),aes(x=catRewLevel,y=hit,color=catRewLevel,shape=catCong,group=catCong),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#00A3A3","#005E5E"),guide = 'none') + ylab('<b>Accuracy</b><br>') + xlab("Reward") +
  coord_cartesian(ylim = c(0.95,0.98)) + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  scale_y_continuous(breaks = c(0.96,0.98)) + scale_x_discrete(labels=c("High Reward" = "High","Medium Reward" = "Medium","Low Reward" = "Low"))
 
dfwc.r.accrt<-summarySEwithin(df.trial.combined, measurevar="AccRT", withinvars=c("catRewLevel","catCong"),idvar="subj_idx",na.rm=TRUE, conf.interval=.95)

pr.accrt <- ggplot() + geom_line(data=dfwc.r.accrt,position=position_dodge(.6),aes(x=catRewLevel,y=AccRT,linetype=catCong,group=catCong)) +
  geom_errorbar(data=dfwc.r.accrt,position = position_dodge(.6),width=0,size=1,aes(x=catRewLevel,ymin=AccRT-ci, ymax=AccRT +ci,color=catRewLevel,group=catCong)) +
  geom_point(data=dfwc.r.accrt,position=position_dodge(.6),aes(x=catRewLevel,y=AccRT,color=catRewLevel,shape=catCong,group=catCong),stat='identity',size=2) + gg.side +
  scale_color_manual(name = "",values=c("#00D9D9","#00A3A3","#005E5E"),guide = 'none') + scale_linetype_discrete(guide='none') + scale_shape_discrete(guide='none') +
  ylab("<b>Reaction Time(s)</b><br>(Correct Responses Only)") + xlab("Reward") +coord_cartesian(ylim = c(0.75,0.9)) + 
  scale_y_continuous(breaks = c(0.8,0.9)) + scale_x_discrete(labels=c("High Reward" = "High","Medium Reward" = "Medium","Low Reward" = "Low"))

```



```{r}
lay <- rbind(c(1,NA,3),
             c(2,NA,4))

plots <- list(pr.accrt,pr.acc,pp.accrt,pp.acc)
grobs <- list()
widths <- list()

for (i in 1:length(plots)){
    grobs[[i]] <- ggplotGrob(plots[[i]])
    widths[[i]] <- grobs[[i]]$widths[2:5]
}

maxwidth <- do.call(grid::unit.pmax, widths)

for (i in 1:length(grobs)){
     grobs[[i]]$widths[2:5] <- as.list(maxwidth)
}

p<-grid.arrange(grobs = grobs, layout_matrix = lay,widths=unit(c(5,0.5,5), c("cm", "cm")),heights=unit(c(5,5),c('cm','cm')))

ggsave(filename = 'Figures/Figure7_cong_combined.pdf',p,units = 'cm',width = 22,height = 11)
```
